# Generated by Django 3.0.8 on 2020-07-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20200718_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='urls',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='textContent',
            new_name='Content',
        ),
    ]
