# Generated by Django 3.0.8 on 2020-07-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20200718_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='pub_date',
        ),
    ]
