# Generated by Django 3.0.8 on 2020-07-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='textContent',
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='url',
            new_name='urlContent',
        ),
    ]
